# Objectif : Identifier les problèmes et appliquer les bonnes pratiques


apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: shopping
type: Opaque
data:
  # echo -n 'admin' | base64 = YWRtaW4=
  username: YWRtaW4=
  # echo -n 'SuperSecretPassword123!' | base64 = U3VwZXJTZWNyZXRQYXNzd29yZDEyMyE=
  password: U3VwZXJTZWNyZXRQYXNzd29yZDEyMyE=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: shopping
data:
  app.environment: "production"
  app.log.level: "INFO"
  
  database.password: "SuperSecretPassword123!"
  jwt.secret: "myJwtSecretKeyThatShouldBeInASecret"
  api.key: "sk-prod-1234567890abcdef"
  smtp.password: "emailPassword456"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-with-secret-annotations
  namespace: shopping
  annotations:
    config.database.password: "SuperSecretPassword123!"
    config.api.key: "sk-prod-1234567890abcdef"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: shopping-backend:latest
          
          env:
            - name: DATABASE_PASSWORD
              value: "SuperSecretPassword123!"
            
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: password

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-script
  namespace: shopping
data:
  init.sh: |
    #!/bin/bash
    export DB_PASSWORD="SuperSecretPassword123!"
    export API_KEY="sk-prod-1234567890abcdef"
    
    # Connexion à la base de données
    psql -h $DB_HOST -U admin -d shopping << EOF
    CREATE USER app_user WITH PASSWORD 'AnotherSecretPassword789!';
    GRANT ALL PRIVILEGES ON DATABASE shopping TO app_user;
    EOF
    
    # Appel API
    curl -H "Authorization: Bearer sk-prod-1234567890abcdef" https://api.example.com/init
